services:
  ble2mqtt:
    image: ble2mqtt:dev
    container_name: ble2mqtt
    hostname: ble2mqtt
    restart: always
    environment:
      TZ: America/Montreal
    volumes:
      - /volume1/docker/ble2mqtt/etc/ble2mqtt.json:/etc/ble2mqtt.json:ro
    network_mode: host
    cap_add:
      - NET_ADMIN
